housekeeping and bugfixes

diff --git a/git-graph b/git-graph
--- a/git-graph
+++ b/git-graph
@@ -18,6 +18,9 @@
 #  along with git-graph.  If not, see <http://www.gnu.org/licenses/>.
 
 
+## constants ##
+
+readonly USE_ANSI_COLOR=$( [[ "$1" == '--no-color' ]] && echo '0' || echo '1' )
 readonly JOIN_CHAR='~'
 readonly HRULE_CHAR='-'
 readonly GRAPH_REGEX="(.+)"
@@ -29,16 +32,17 @@ readonly STAT_REGEX="\[(.)\]"
 readonly MSG_REGEX="(.*)"
 readonly REFS_REGEX="\((.*)\)"
 readonly GIT_LOG_FMT="git log --graph --date=short -n %d --pretty=format:"
-readonly LOG_FMT="%h$JOIN_CHAR%ad$JOIN_CHAR%an$JOIN_CHAR[%GS]$JOIN_CHAR[%G?]$JOIN_CHAR%s$JOIN_CHAR(%D)"
-readonly LOG_REGEX="^$GRAPH_REGEX $ID_REGEX$JOIN_CHAR$DATE_REGEX$JOIN_CHAR$AUTHOR_REGEX$JOIN_CHAR$SIG_REGEX$JOIN_CHAR$STAT_REGEX$JOIN_CHAR$MSG_REGEX$JOIN_CHAR$REFS_REGEX$"
-readonly CWHITE='\033[0;37m'
-readonly CGREEN='\033[0;32m'
-readonly CYELLOW='\033[0;33m'
-readonly CRED='\033[0;31m'
-readonly CBLUE='\033[0;34m'
-readonly CEND='\033[0m'
+readonly LOG_FMT="%h${JOIN_CHAR}%ad${JOIN_CHAR}%an${JOIN_CHAR}[%GS]${JOIN_CHAR}[%G?]${JOIN_CHAR}%s${JOIN_CHAR}(%D)"
+readonly LOG_REGEX="^${GRAPH_REGEX} ${ID_REGEX}${JOIN_CHAR}${DATE_REGEX}${JOIN_CHAR}${AUTHOR_REGEX}${JOIN_CHAR}${SIG_REGEX}${JOIN_CHAR}${STAT_REGEX}${JOIN_CHAR}${MSG_REGEX}${JOIN_CHAR}${REFS_REGEX}$"
+readonly CWHITE=$(  (( $USE_ANSI_COLOR )) && echo '\033[0;37m')
+readonly CGREEN=$(  (( $USE_ANSI_COLOR )) && echo '\033[0;32m')
+readonly CYELLOW=$( (( $USE_ANSI_COLOR )) && echo '\033[0;33m')
+readonly CRED=$(    (( $USE_ANSI_COLOR )) && echo '\033[0;31m')
+readonly CBLUE=$(   (( $USE_ANSI_COLOR )) && echo '\033[1;34m')
+readonly CEND=$(    (( $USE_ANSI_COLOR )) && echo '\033[0m'   )
 readonly CGOOD=$CGREEN
 readonly CUNKNOWN=$CYELLOW
+readonly CEXPIRED=$CYELLOW
 readonly CBAD=$CRED
 readonly CNONE=$CWHITE
 readonly ID_COLOR=$CNONE
@@ -46,6 +50,11 @@ readonly DATE_COLOR=$CNONE
 readonly AUTHOR_COLOR=$CNONE
 readonly MSG_COLOR=$CNONE
 readonly REF_COLOR=$CBLUE
+#(deferred) readonly N_COMMITS
+#(deferred) readonly REF
+
+
+## variables ##
 
 declare -a graphs=()
 declare -a ids=()
@@ -57,41 +66,58 @@ declare -a refs=()
 author_w=0
 
 
-# helpers
+## helpers ##
 
-function DoesBranchExist # (branch_name)
+DoesBranchExist() # (branch_name)
 {
-  [ "$(git branch | grep -G " $1$")" ] && echo 1 || echo 0
+  local branch_name=$1
+
+  [ "$branch_name" -a "$(git branch | grep -G " $branch_name$")" ] && echo 1 || echo 0
 }
 
-function DoesTagExist # (tag_name)
+DoesTagExist() # (tag_name)
 {
-  [ "$(git tag    | grep -G "$1$")"  ] && echo 1 || echo 0
+  local tag_name=$1
+
+  [ "$tag_name" -a "$(git tag | grep -G "$tag_name$")" ] && echo 1 || echo 0
 }
 
-function JoinChars # (a_string)
+ValidateRef() # (ref) # where ref is a branch_name, tag_name, or file_name
 {
-  echo "${1// /$JOIN_CHAR}"
+  local ref=$1
+
+  (( $(DoesBranchExist $ref) )) || (( $(DoesTagExist $ref) )) || [ -f "$ref" ] || ref=''
+
+  echo $ref ; [[ -n "$ref" ]] ;
 }
 
-function FilterJoinChars # (a_string)
+JoinChars() # (a_string)
 {
-   echo $1 | tr "$JOIN_CHAR" " "
+  local a_string=$1
+
+  echo "${a_string// /$JOIN_CHAR}"
 }
 
+FilterJoinChars() # (a_string)
+{
+  local a_string=$1
+
+  echo $a_string | tr "$JOIN_CHAR" " "
+}
+
+
+## main entry ##
 
 # parse cli args
 while getopts 'n:' arg
-do case "${arg}" in
-        n) n_commits="${OPTARG}" ;;
-        *) echo "Invalid argument: '${arg}'" ;;
-    esac
+do    case "${arg}" in
+           n) n_commits="${OPTARG}" ;;
+           *) echo "Invalid argument: '${arg}'" ;;
+      esac
 done
 readonly N_COMMITS=${n_commits:-12}
-ref=${!OPTIND}
-(( $(DoesBranchExist $1) )) || (( $(DoesTagExist $1) )) || [ -f "$1" ] && readonly REF=$1
-[ "$REF" != "$1" ] && echo -e "no such branch, tag, or file: '$1'\n"
-
+readonly REF=$(ValidateRef "${!OPTIND}")
+[ -n "${!OPTIND}" ] && [ -z "$REF" ] && echo "no such branch, tag, or file: '${!OPTIND}'"
 
 # compile results
 while read -r commit
@@ -115,18 +141,19 @@ do
    [ "$ref"         ] ||        refs=(   ${refs[@]}    "$JOIN_CHAR"          )
 
    case $stat in
-        'G') sig_colors=(${sig_colors[@]} "$CGOOD"   ) ;; # valid signature
-        'X') sig_colors=(${sig_colors[@]} "$CGOOD"   ) ;; # valid signature that has expired
-        'U') sig_colors=(${sig_colors[@]} "$CUNKNOWN") ;; # valid signature with unknown validity
+        'G') sig_colors=(${sig_colors[@]} "$CGOOD"   ) ;; # good signature
+        'X') sig_colors=(${sig_colors[@]} "$CGOOD"   ) ;; # good signature that has expired
+        'U') sig_colors=(${sig_colors[@]} "$CUNKNOWN") ;; # good signature with unknown trust
         'E') sig_colors=(${sig_colors[@]} "$CUNKNOWN") ;; # cannot be checked (e.g. missing key)
         'B') sig_colors=(${sig_colors[@]} "$CBAD"    ) ;; # bad signature
-        'Y') sig_colors=(${sig_colors[@]} "$CBAD"    ) ;; # valid signature made by an expired key
-        'R') sig_colors=(${sig_colors[@]} "$CBAD"    ) ;; # valid signature made by a revoked key
+        'Y') sig_colors=(${sig_colors[@]} "$CEXPIRED") ;; # good signature made by an expired key
+        'R') sig_colors=(${sig_colors[@]} "$CBAD"    ) ;; # good signature made by a revoked key
         'N') sig_colors=(${sig_colors[@]} "$CNONE"   ) ;; # no signature
    esac
 
    [ ${#author} -gt $author_w ] && author_w=${#author}
-done <<<$($(printf "$GIT_LOG_FMT" $N_COMMITS)"$LOG_FMT" $REF)
+# done < <($(printf "$GIT_LOG_FMT" $N_COMMITS)"$LOG_FMT" $REF)
+done < <(echo "$($(printf "$GIT_LOG_FMT" $N_COMMITS)"$LOG_FMT" $REF)")
 
 # pretty print results
 for (( result_n = 0 ; result_n < ${#ids[@]} ; result_n++ ))
@@ -139,7 +166,7 @@ do graph=${graphs[$result_n]}
    msg=${msgs[$result_n]}
    ref=${refs[$result_n]}
    sig_color=${sig_colors[$result_n]}
-   pad="%$(($author_w - ${#author}))s"
+   pad="%$(( $author_w - ${#author} ))s"
 
   [ "$ID_COLOR"         ] && id_color=$ID_COLOR      || id_color=$sig_color
   [ "$DATE_COLOR"       ] && date_color=$DATE_COLOR  || date_color=$sig_color
@@ -150,8 +177,8 @@ do graph=${graphs[$result_n]}
 #    printf "$graph_color$(FilterJoinChars $graph) $CEND"
    printf "$id_color$id $CEND"
    printf "$date_color$date $CEND"
-   printf "$author_color$(FilterJoinChars $author)$CEND"
-   printf "$msg_color:$pad $(FilterJoinChars $msg)$CEND"
+   printf "$author_color%s$CEND" "$(FilterJoinChars $author)"
+   printf "$msg_color:$pad %s$CEND" '' "$(FilterJoinChars $msg)"
    [ "$ref" != "$JOIN_CHAR" ] && printf " $ref_color($(FilterJoinChars $ref))$CEND"
    [ "$sig" != "$JOIN_CHAR" ] && printf " $sig_color[$(FilterJoinChars $sig)]$CEND"
    printf "\n"
